import os
from datetime import datetime
from .config import OUTPUT_DIR

def save_bmad_markdown(task_name: str, instruction: str, matched_skills: list, ingested_data: dict, analysis_result: str):
    """Generates Knowledge Silos-compliant Markdown output files."""
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = "".join(c if c.isalnum() else "_" for c in task_name)[:30]
    filename = f"ks_report_{safe_name}_{timestamp}.md"
    file_path = os.path.join(OUTPUT_DIR, filename)

    skills_str = ", ".join([s['name'] for s in matched_skills])
    sources_str = ", ".join(list(ingested_data.keys())) if ingested_data else "None"

    markdown_content = f"""# Knowledge Silos Execution Report

## Metadata
- **Generated At:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Matched Agent Skills:** {skills_str}
- **Ingested Sources:** {sources_str}

---

## 1. User Instruction
> {instruction}

---

## 2. Ingested Context Summary
"""
    for doc_name in ingested_data.keys():
        markdown_content += f"- **Source:** `{doc_name}`\n"

    markdown_content += f"""
---

## 3. Knowledge Silos Agent Analysis & Execution
{analysis_result}

---
*Generated by Knowledge Silos Python Orchestrator Framework.*
"""

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)

    return file_path